### ISSUE TITLE
XYZ logo replacement

### ISSUE THREAD

**Issue by jevets** [evendev/gorge-kirby#11]
Please shoot over a better quality logo, stole [current](http://gorge.dev.evendev.com/assets/img/groovy.xyz.png) from a mock, fuzzy

**Comment by jevets** [comment]
<img width="635" alt="screen shot 2016-01-08 at 7 28 34 am" src="https://cloud.githubusercontent.com/assets/1187075/12197942/aa4fb1b0-b5d9-11e5-8538-73681b9fe2a8.png">

**Comment by groovyxyz** [comment]
![groovy-xyz-commercial-design](https://cloud.githubusercontent.com/assets/13220587/12199792/d968f2ea-b5e8-11e5-882b-0818081c05de.png)

**Comment by groovyxyz** [comment]
image is posted in previous comment. Also available in the first assets folder had sent you.
