### ISSUE TITLE
Sketchy font

### ISSUE THREAD

**Issue by jevets** [evendev/gorge-kirby#14]
Sara requested the previous version of sketchy font I had going, was Google's "Covered by Your Grace"

https://www.google.com/fonts/specimen/Covered+By+Your+Grace

I'm going to put it back to that now, let me know if need to change it back to yours, no matter to me.

**Comment by groovyxyz** [comment]
Have an updated homepage-poster.jpg for you, replaces the font with 'covered by you grace':
![homepage-poster](https://cloud.githubusercontent.com/assets/13220587/12257318/6e9b10ea-b8d3-11e5-82db-7a1dc4632569.jpg)
