### ISSUE TITLE
Favicons/touch

### ISSUE THREAD

**Issue by jevets** [evendev/gorge-kirby#16]
I'm using the favicon from current site, http://gorge.dev.evendev.com/favicon.ico

If you want new ones, and/or apple touch, shoot me a square master img or an iconfier zip

Otherwise, will just use this one favicon

**Comment by groovyxyz** [comment]
Here's an update iconified:
[iconified.zip](https://github.com/evendev/gorge-kirby/files/83949/iconified.zip)
