### ISSUE TITLE
Tabs images on /zipline

### ISSUE THREAD

**Issue by jevets** [evendev/gorge-kirby#18]
> icons for what to expect & requirements tabs. Mocks included, size/spacing are just rough suggestion, whatever works best/standard/conventional markup up to you. snorts, any questions

**Comment by groovyxyz** [comment]
Let me know any troubles/questions regarding mocks/assets for these. Two tab sections provided, other tabs will tackle post launch.

**Comment by jevets** [comment]
[tabs.zip](https://github.com/evendev/gorge-kirby/files/104894/tabs.zip)
