### ISSUE TITLE
Sara to clarify SEO work that Fuel did

### ISSUE THREAD

**Issue by jevets** [evendev/gorge-kirby#20]
Doesn't look like Fuel did any SEO work.

No focus keywords set, no meta descriptions, no tracking code on contact form, analytics not even integrated...

**Comment by jevets** [comment]
@groovyxyz Any knowledge on this?

**Comment by groovyxyz** [comment]
No knowledge of this -- Sara mentioned they asked her a few basic questions, beyond that uncertain.

Hunch is old school seo approach at best -- if anything at all. I still lean toward frequent content updates, more frequent page upgrades and expanding content, will be recommending monthly-ish projects focusing on expanding and maturing given section of website. Can share my notes if interested.
