### ISSUE TITLE
Default page header image replacement

### ISSUE THREAD

**Issue by jevets** [evendev/gorge-kirby#7]
Currently using a 892px w image
http://gorge.dev.evendev.com/assets/img/default-header.png

Need something bigger, resorting to `background-size: contain` for now

**Comment by groovyxyz** [comment]
Proper size image attached -- found out issue here, some bug in my photoshop causing some exports to size at 81.93%, dumb horse shit.
![default-header](https://cloud.githubusercontent.com/assets/13220587/12189090/fd1efbe0-b588-11e5-96d2-cd0fc94df980.png)
