### ISSUE TITLE
Correct orange hex?

### ISSUE THREAD

**Issue by jevets** [evendev/gorge-kirby#8]
The hex I'm using for orange is `#fd5004`

Is this correct? Mocks appear brighter, less saturated. Chance it was incorrect similar to CMYK non black logo issue?

**Comment by jevets** [comment]
Footer logo orange doesn't match text/link orange

<img width="708" alt="screen shot 2016-01-08 at 6 49 47 am" src="https://cloud.githubusercontent.com/assets/1187075/12197331/06f859ea-b5d4-11e5-9c0b-ac7a6073e3c8.png">

**Comment by groovyxyz** [comment]
Yes they are different oranges. The logo uses #fd8204 lighter orange, the text orange color is # fd5004, good to keep using fd5004 for text orange color.

**Comment by jevets** [comment]
Ok, just checking. Mocks show same orange
